<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<ul class="navbar-nav mx-auto mb-2 mb-md-0">
  <?php foreach ($container as $page): ?>
    <?php if (!$this->navigation()->accept($page)) {
      continue;
    } ?>
    <?php /* @var $page Laminas\Navigation\Page\Mvc */?>
    <?php $hasChildren = $page->hasPages() ?>
    <?php if (!$hasChildren): ?>
      <li class="nav-item">
        <a class="nav-link text-dark <?php echo $page->isActive() ? 'active' : ''; ?>" <?php echo $page->isActive() ? 'aria-current="page"' : ''; ?> href="<?php echo $page->getHref() ?>">
          <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
        </a>
      </li>
    <?php else: ?>
      <?php
      //check if access is allowed at least one item
      $access = false;
      foreach ($page->getPages() as $child) {
        if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
          $access = true;
        }
      }
      if ($access):
        ?>
        <li class="nav-item dropdown">
          <?php $idName = str_replace(' ', '', $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain()))); ?>
          <a class="nav-link text-dark dropdown-toggle" id="<?php echo $idName; ?>" href="#" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
            <b class="caret"></b>
          </a>
          <?php echo $this->partial('common/bootstrap-subnavigation.phtml', ['container' => $container, 'children' => $page->getPages(), 'level' => 1, 'idName' => $idName]); ?>
        </li>
      <?php endif; ?>
    <?php endif ?>
  <?php endforeach ?>
  <li class="nav-item">
    <button class="nav-link text-dark border-0 bg-transparent" data-bs-toggle="modal" data-bs-target="#searchModal"
      aria-label="Search">
      <i class="fas fa-search" aria-hidden="true" title="Search">
      </i>
    </button>
    <!-- Modal -->
    <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="modal-title" id="searchModalLabel">
              <?php echo $translate('Site Search'); ?>
            </h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <!-- check if solr/search module is activated by checking if the helper is present, if not use default search -->
            <?php $searchForm = null; ?>
            <?php if ($this->getHelperPluginManager()->has('getSearchFormForSite')): ?>
              <?php $searchForm = $this->getSearchFormForSite($site); ?>
            <?php endif; ?>
            <?php if ($searchForm): ?>
              <?php echo $searchForm ?>
            <?php else: ?>
              <?php echo $this->partial('common/search-form'); ?>
              <div class="collapse mt-3" id="collapseAdvanced">
                <h3>
                  <?php echo $translate('Advanced Item Search'); ?>
                </h3>
                <?php echo $this->partial('common/advanced-search-form'); ?>
              </div>
            <?php endif; ?>
          </div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAdvanced"
              aria-expanded="false" aria-controls="collapseAdvanced">
              <?php echo $translate('Advanced Search Options'); ?>
            </button>
          </div>
        </div>
      </div>
    </div>

  </li>
</ul>