<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();

$this->htmlElement('body')->appendAttribute('class', 'item-set resource browse');
$totalResults = $this->pagination()->getPaginator()->getTotalCount();
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Date'),
        'value' => 'dcterms:date'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>

<div class="container pt-2 pb-3 pt-md-5 pb-md-4">
  <div class="row justify-content-center">
    <div class="col">
      <?php echo $this->pageTitle($translate('Collections'), 2); ?>

      <?php if ($this->searchFilters()): ?>
        <div class="results">
          Showing <?php echo number_format($totalResults); ?> result<?php echo ($totalResults == 1)? '' : 's'; ?> for: <?php echo $this->searchFilters(); ?>
        </div>
      <?php else: ?>
        <div class="results">
          Showing <?php echo number_format($totalResults); ?> result<?php echo ($totalResults == 1)? '' : 's'; ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
</div>
<div class="container pt-2 pb-3 pt-md-4 pb-md-3">
  <div class="row justify-content-center">
    <div class="col">
      <ul class="nav justify-content-between browse-controls">
        <li class="nav-item"><?php echo $this->sortSelector($sortHeadings); ?></li>
        <li class="nav-item d-none d-md-block">
          <div class="btn-group" role="group" aria-label="Layout View">
            <button type="button" class="btn btn-secondary active list" aria-pressed="true">
              <i class="fas fa-list" aria-hidden="true" title="List View">
                <span class="visually-hidden">List View</span>
              </i>
            </button>
            <button type="button" class="btn btn-secondary grid">
              <i class="fas fa-th" aria-hidden="true" title="Grid View">
                <span class="visually-hidden">Grid View</span>
              </i>
            </button>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>


<?php $this->trigger('view.browse.before'); ?>
<div class="container list pt-2 pb-3 pt-md-3 pb-md-4">
  <div class="row list" id="browse-container">
    <?php
    $collectionCount = 1;
    $headingTerm = $this->siteSetting('browse_heading_property_term');
    $bodyTerm = $this->siteSetting('browse_body_property_term');
    foreach ($itemSets as $itemSet):
    $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => ($filterLocale ? [$lang, ''] : null)]) : $itemSet->displayTitle(null, ($filterLocale ? [$lang, ''] : null));
    $body = $bodyTerm ? $itemSet->value($bodyTerm, ['lang' => ($filterLocale ? [$lang, ''] : null)]) : $itemSet->displayDescription(null, ($filterLocale ? [$lang, ''] : null));
    ?>
      <div class="col item-container">
        <div class="card border-0">
          <?php echo $itemSet->linkRaw($this->thumbnail($itemSet, 'medium', ['class' => 'browse-thumbnail shadow-sm rounded', 'alt' => $heading]), null, ['class' => 'card-img']); ?>
          <div class="card-body overflow-hidden">
            <h3 class="item-title"><?php echo $itemSet->link($heading, null, ['class'=> 'text-dark text-decoration-none']); ?></h3>
            <?php echo $this->ItemDetailsHelper($itemSet); ?>

            <?php if ($contributors = $itemSet->value('dcterms:contributor', ['all' => true, 'lang' => ($filterLocale ? [$lang, ''] : null)])): ?>
              <div class="contributors fst-italic">
                <?php
                $i = 1;
                $len = count($contributors);
                ?>
                <?php foreach ($contributors as $contributor): ?>
                  <?php echo $contributor->asHtml(); ?>
                  <?php if ($len > $i): ?>
                    <?php echo "; "; ?>
                  <?php endif; ?>
                  <?php $i++; ?>
                <?php endforeach; ?>
              </div>
            <?php endif; ?>
            <?php if ($abstract = $itemSet->value('dcterms:abstract', ['lang' => ($filterLocale ? [$lang, ''] : null)])): ?>
            <div class="abstract"><?php echo $abstract->asHtml(); ?></div>
            <?php elseif ($description = $itemSet->value('dcterms:description', ['lang' => ($filterLocale ? [$lang, ''] : null)])): ?>
            <div class="description"><?php echo $description->asHtml(); ?></div>
            <?php endif; ?>
            <div class="item-count collection-search">
              <span class="fst-italic">
                <?php echo $itemSet->itemCount() . " items"; ?>
              </span>

              <button class="text-dark border-0 bg-transparent" data-bs-toggle="modal" data-bs-target="#collectionSearchModal-<?php echo $collectionCount; ?>" aria-label="Search the <?php echo $heading; ?> collection">
                <i class="fas fa-search" aria-hidden="true" title="Search the <?php echo $heading; ?> collection">
                </i>
              </button>
              <!-- Modal -->
              <div class="modal fade" id="collectionSearchModal-<?php echo $collectionCount; ?>" tabindex="-1" aria-labelledby="collectionSearchModalLabel-<?php echo $collectionCount; ?>" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-lg">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title" id="collectionSearchModalLabel-<?php echo $collectionCount; ?>">Search the <?php echo $heading; ?> collection</h4>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <!-- check if solr/search module is activated by checking if the helper is present, if not use default search -->
                    <?php
                      if ($this->getHelperPluginManager()->has('getSearchFormForSite')) {
                          $formURL = $this->url('site/search', ['__NAMESPACE__' => 'Search\Controller', 'controller' => 'index', 'action' => 'search'], true);
                          $inputName = 'q';
                          $hiddenName = 'item_set_id[]';
                      } else {
                          $formURL = $this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], true);
                          $inputName = 'fulltext_search';
                          $hiddenName = 'item_set_id';
                      }

                    ?>
                    <div class="modal-body">
                      <form class="d-flex" action="<?php echo $this->escapeHtml($formURL); ?>" id="search-form">
                        <input type="hidden" id="item_set_id" name="<?php echo $hiddenName; ?>" value="<?php echo $itemSet->id(); ?>">
                        <div class="input-group">
                          <input name="<?php echo $inputName; ?>" type="search" autocomplete="off" class="form-control form-control-lg" value="" placeholder="<?php echo $translate('Search this collection'); ?>" aria-label="<?php echo $translate('Search this collection'); ?>">
                          <button class="btn btn-secondary" type="submit" aria-label="<?php echo $translate('Search'); ?>">
                            <i class="fas fa-search" title="<?php echo $translate('Search'); ?>" aria-hidden="true"></i>
                          </button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <?php $collectionCount++; ?>
    <?php endforeach; ?>
  </div>
</div>
<?php $this->trigger('view.browse.after'); ?>
<div class="container pb-5">
  <div class="row justify-content-center pagination-row">
    <div class="col-auto">
      <?php echo $this->pagination(); ?>
    </div>
  </div>
</div>
