<?php
/*
 * Copyright BibLibre, 2016
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
?>

<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => ($filterLocale ? [$lang, ''] : null)]) : $resource->displayTitle(null, ($filterLocale ? [$lang, ''] : null));

?>
<div class="col item-container">
  <div class="card border-0">
    <?php echo $resource->linkRaw($this->thumbnail($resource, 'medium', ['class' => 'browse-thumbnail shadow-sm rounded', 'alt' => $heading]), null, ['class' => 'card-img']); ?>
    <div class="card-body overflow-hidden">
      <h3 class="item-title">
        <?php echo $resource->link($heading, null, ['class' => 'text-dark text-decoration-none']); ?>
      </h3>
      <?php echo $this->CreatorHelper($resource); ?>
      <?php echo $this->ItemDetailsHelper($resource); ?>
      <?php if ($abstract = $resource->value('dcterms:abstract', ['lang' => ($filterLocale ? [$lang, ''] : null)])): ?>
        <div class="abstract">
          <?php echo $abstract->asHtml(); ?>
        </div>
      <?php elseif ($description = $resource->value('dcterms:description', ['lang' => ($filterLocale ? [$lang, ''] : null)])): ?>
        <div class="description">
          <?php echo $description->asHtml(); ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
</div>