<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->appendAttribute('lang', $this->lang())->appendAttribute('class', 'h-100');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($site->title())->setSeparator(' · ');
$this->headLink(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => $this->assetUrl('img/favicon.ico')], 'PREPEND')
  ->prependStylesheet($this->assetUrl('css/style.css'))
  ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.css', 'screen', null, ['integrity' => 'sha512-MKxcSu/LDtbIYHBNAWUQwfB3iVoG9xeMCm32QV5hZ/9lFaQZJVaXfz9aFa0IZExWzCpm7OWvp9zq9gVip/nLMg==', 'crossorigin' => 'anonymous'])
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css', 'screen', null, ['integrity' => 'sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=', 'crossorigin' => 'anonymous'])
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css', 'screen', null, ['integrity' => 'sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU', 'crossorigin' => 'anonymous']);
$this->headScript()
  ->prependFile($this->assetUrl('js/advanced-search.js', 'Omeka'))
  ->prependFile($this->assetUrl('js/theme.js'))
  ->prependFile($this->assetUrl('js/global.js', 'Omeka'))
  ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.min.js', 'text/javascript', ['integrity' => 'sha512-1mDhG//LAjM3pLXCJyaA+4c+h5qmMoTc7IuJyuNNPaakrWT9rVTxICK4tIizf7YwJsXgDC2JP74PGCc7qxLAHw==', 'crossorigin' => 'anonymous'])
  ->prependFile('https://unpkg.com/infinite-scroll@4.0.1/dist/infinite-scroll.pkgd.min.js', 'text/javascript')
  ->prependFile('https://cdn.jsdelivr.net/npm/corejs-typeahead@1.3.1/dist/typeahead.bundle.min.js', 'text/javascript', ['integrity' => 'sha256-xZuy7z/QR1H5FKCYUbRDj4yvcyMEyVIg4iQUhs8MI+w=', 'crossorigin' => 'anonymous'])
  ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js', 'text/javascript', ['integrity' => 'sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ', 'crossorigin' => 'anonymous'])
  ->prependFile('https://code.jquery.com/jquery-3.6.0.min.js', 'text/javascript', ['integrity' => 'sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=', 'crossorigin' => 'anonymous']);
$this->trigger('view.layout');
$userBar = $this->userBar('common/theme-site-slug-as-domain-user-bar');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-9G9SWC42GS"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'G-9G9SWC42GS');
  </script>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
</head>

<?php echo $this->htmlElement('body')->appendAttribute('class', 'd-flex flex-column h-100'); ?>
<a class="visually-hidden-focusable" href="#content">
  <?php echo $this->translate('Skip to main content'); ?>
</a>
<header class="flex-shrink-0">
  <?php if ($userBar) : ?>
    <nav class="navbar navbar-expand-md d-none d-md-block user-info">
      <div class="container-fluid">
        <div class="navbar-collapse">
          <?php echo $userBar; ?>
        </div>
      </div>
    </nav>
  <?php endif; ?>
  <div class="container pt-5 pb-2 d-none d-md-block">
    <div class="row justify-content-center">
      <div class="col-auto">
        <a href="/" class="logo text-dark text-decoration-none">
          <h1 class="visually-hidden">
            <?php echo $escape($site->title()); ?>
          </h1>
          <img src="<?php echo $this->assetUrl('img/fit-institutional-repository-green.png'); ?>" title="Logo"
            alt="FIT Institutional Repository Logo">
        </a>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-md navbar-light">
    <div class="container-fluid">
      <a class="navbar-brand  d-md-none" href="<?php echo $site->url(); ?>">
        <img src="<?php echo $this->assetUrl('img/fit-institutional-repository-stacked-green.png'); ?>"
          alt="FIT Institutional Repository">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <?php echo $site->publicNav()->menu()->renderPartialWithParams(['site' => $site,], null, 'common/bootstrap-navigation.phtml'); ?>
        <?php if ($userBar) : ?>
          <div class="d-md-none user-info">
            <?php echo $userBar; ?>
          </div>
        <?php endif; ?>
      </div>
    </div>
  </nav>
</header>
<div class="flex-shrink-0" id="content" role="main">
  <?php echo $this->content; ?>
</div>
<footer class="footer mt-auto py-3 py-md-5 border-top border-light">
  <div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-5">
        <a href="https://www.fitnyc.edu">
          <img class="mb-3" src="<?php echo $this->assetUrl('img/wordmark-black-1-line.png'); ?>" alt="FIT SUNY Logo"
            id="fit-logo">
        </a>
        <p class="small">
          ©
          <?php echo date("Y"); ?> Fashion Institute of Technology
          <br>
          All rights reserved.
        </p>
        <p class="text-left">This site is an initiative of the FIT Library.</p>
        <ul class="list-inline mb-0">
          <li class="list-inline-item"><a class="link-secondary" href="https://www.fitnyc.edu/academics/library/"
              aria-label="FIT Library Homepage"><i class="fas fa-home" aria-hidden="true"
                title="FIT Library Homepage"></i><span class="sr-only">FIT Library Homepage</span></a></li>
          <li class="list-inline-item"><a class="link-secondary" href="https://www.facebook.com/FITLibrary"
              aria-label="FIT Library Facebook"><i class="fab fa-facebook" aria-hidden="true"
                title="FIT Library Facebook"></i><span class="sr-only">FIT Library Facebook</span></a></li>
          <li class="list-inline-item"><a class="link-secondary" href="https://twitter.com/FITLibrary"
              aria-label="FIT Library Twitter"><i class="fab fa-twitter" aria-hidden="true"
                title="FIT Library Twitter"></i><span class="sr-only">FIT Library Twitter</span></a></li>
          <li class="list-inline-item"><a class="link-secondary" href="https://www.tiktok.com/@fitnyclibrary"
              aria-label="FIT Library TikTok"><i class="fab fa-tiktok" aria-hidden="true"
                title="FIT Library TikTok"></i><span class="sr-only">FIT Library TikTok</span></a></li>
          <li class="list-inline-item"><a class="link-secondary" href="https://www.instagram.com/fitnyclibrary/"
              aria-label="FIT Library Instagram"><i class="fab fa-instagram" aria-hidden="true"
                title="FIT Library Instagram"></i><span class="sr-only">FIT Library Instagram</span></a></li>

        </ul>
      </div>
    </div>
  </div>
</footer>
</body>

</html>